name: Lint

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2.1.2
      with:
        node-version: "12"

    - name: Install dependencies
      run: npm ci

    - name: Run Prettier
      run: npm run format
